/* XPM */
static char * fly8_xpm[] = {
"64 64 5 1",
" 	c #51445144FBEE",
".	c #3CF3FBEE34D3",
"X	c #FBEE14514103",
"o	c #FFFF9A694924",
"O	c #FFFF7DF70000",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"                                                                ",
"               .......................................          ",
"               .......................................          ",
"               ..                                   ..          ",
"               ..                                   ..          ",
"               ..  ...............................  ..          ",
"               ..  . . . . . . . . . . . . . . . .  ..          ",
"               ..  .               .             .  ..          ",
"               ..  .                             .  ..          ",
"               ..                XX  XXXXX          ..          ",
"               ..                XX  XXXXX          ..          ",
"               ..                                   ..          ",
"               ..                                   ..          ",
"               ..                   ....            ..          ",
"ooo            ..                 ..    ..          ..          ",
"ooooooo        ..                .        .         ..          ",
"ooooooooooo    ..                .        .         ..          ",
"ooooooooooooooo..               .          .        ..          ",
"ooooooooooooooo..ooo            .    ..    .        ..          ",
"ooooooooooooooo..o......        .    ..    . ...... ..          ",
"ooooooooooooooo..o.oooo.oooo    .          . .    . ..          ",
"ooooooooooooooo..o......oooooooo .        .  ...... ..          ",
"ooooooooooooooo..oooooooooooooooo.ooo     .         ..          ",
"ooooooooooooooo..ooooooooooooooooo..oooo..          ..          ",
"ooooooooooooooo..ooooooooooooooooooo....ooooo       ..          ",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooo  ..          ",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..          ",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooo      ",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooo  ",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo..ooooooooooooooooooooooooooooooooooo..oooooooooo",
"ooooooooooooooo.......................................oooooooooo",
"ooooooooooooooo.......................................oooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"oooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo",
"OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO"};
