# define F_DUPFD        0
# define F_GETFD        1
# define F_SETFD        2
# define F_GETFL        3
# define F_SETFL        4
# define F_GETLK        7
# define F_SETLK        8
# define F_SETLKW       9
# define O_NONBLOCK     0x00000004
